name = "OpenADMIXTURE"
uuid = "425c031d-9e5b-441b-a07e-4acde9a966a3"
authors = ["Seyoon Ko <kos@ucla.edu> and contributors"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SnpArrays = "4e780e97-f5bf-4111-9dc4-b70aaf691b06"
SparseKmeansFeatureRanking = "a6138be3-5d3e-4f3e-9009-7e37efc59f36"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Adapt = "3.3, 4"
Formatting = "0.4"
LoopVectorization = "0.12"
Polyester = "0.7"
ProgressMeter = "1"
Requires = "1.3"
SnpArrays = "0.3"
SparseKmeansFeatureRanking = "0.1"
StableRNGs = "1.0.2"
Suppressor = "0.2"
julia = "1.6"

[extras]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
